"base_path" : "."
"base_url" : "https://crowdin.com"

"commit_message": "[ci skip]"

files: [
  {
    "source" : "/src/languages/en-US/**/*.json",
    "translation" : "/src/languages/%locale%/**/%original_file_name%"
  }
]
